### ISSUE TITLE
installation on linux

### ISSUE THREAD

**Issue by feqifei** [stakeyourada/Kongo#9]
Hi, I tried to install it on my linux node, but after unzipping (tar) it I don't find the executable Kongo within the folder.
Which step am I missing?

**Comment by stakeyourada** [comment]
Sorry there was a problem with the release step compressing the files which missed some due to an incorrect file matching pattern.  A new release is being uploaded soon to address.

**Comment by stakeyourada** [comment]
new release is available, thx 
https://github.com/stakeyourada/Kongo/releases/tag/v1.0.1-beta
